#
# IFJ 2017 project
#	File			Makefile
#	Description		Makefile for gcc
#	Author			Michal Zilvar (xzilva02)
#	Last update		10:45, 06-10-2017

CFLAGS=-std=c99 -Wall -pedantic -g
NAME=IFJ17
CC=gcc
OBJ=main.o scanner.o string.o

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) -o $(NAME) $(OBJ)

